state: ld
environment: qa

source:
  mysql:
    database: ld1

targets:
  postgres:
    mapping: pg_bss_mapping_qa
    inventory: pg_bss_inventory_qa
    subscriber: pg_bss_subscriber_qa

enabled_modules:
  - mapping
  - inventory
  - subscriber
